# Specify Base Image
FROM node:alpine

# Work Directory
WORKDIR /usr/app

# COPY Files
COPY ./package.json .

# Install Dependencies
RUN npm install

# Startup Command
CMD ["npm", "start"]
